### ISSUE TITLE
dataset_to_json.py running into errors

### ISSUE THREAD

**Issue by osmalpkoras** [zhuyunqi96/medreportsum#1]
Hello,

I have downloaded the mimic iii dataset from physionet and run the dataset_to_json.py script. However, it is running into an error that is caused by trying to access a non-existent column in line 53:
```
check_subject = chunk[chunk['CATEGORY'] == tgt_column]
```

I checked some csv files, and none had the CATEGORY column. Does the script need an older version of the mimic iii dataset, or is there a mistake in script?

Kind regards

**Comment by dongziyu1016** [comment]
Hi, I also encountered this problem. How should I solve it?
